name: MyWorkFlow

on:
  push:
    branches: [ main, dev ]
  schedule:
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print time
        run: date
      
