name: MyWorkFlow

on:
  schedule:
    - cron: '40 9 5 10 2'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print time
        run: date
      
